---
title: "Mini Learning Analytics Assignment - Network Analysis"
output: html_document
df_print: paged
author: Renato Russo
date: February, 24, 2022
---

This is a notebook that documents my first network analysis.

In this project, I gather comments from YouTube videos of president Jair Bolsonaro in conversations with his followers.
I am interested in knowing whether specific topics that show up in the conversations also appear in the comments--that is, how much do the videos set the tone for the comments? In his conversations, the president sometimes suggest debatable theories to explain topics in politics and economy, for example, that mayors and state governors have a role in economic decline during the pandemic.

I compare two videos--one from November 2020, and one from February 2022--to see if comments in both mention mayors and governors, one of the themes in the first video.

# Preparation
I'll first load all the libraries necessary and authenticate my credentials for YouTube comments scraping.
```{r}
library(httpuv) #httpuv package needed to run the ytoauth()
library(tidyverse) #used for the pipe operator %>%, part of magrittr; and tibble()
#library(tidygraph)
library(tuber) #used for yt_oauth(), get_all_comments()
library(tidytext) #used for unnest_tokens() other text analysis functions in this project 
library(tm) #used here to remove stop words
library(widyr) #used for pairwise count (pairwise_count())
library(ggraph) #used for the co-occurence chart
library(igraph) #used for the co-occurence chart

YT_client_id <- "113759878461-gp15t6i0l6v8cms91r1hp2v44que1dip.apps.googleusercontent.com"
YT_client_secret <- "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"

```
# Video 1

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

